# Generated by Django 5.1.5 on 2025-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True, unique=True)),
                ('contact_no', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('profile_image', models.ImageField(null=True, upload_to='Admin/profile_image/')),
                ('pan_card_number', models.CharField(max_length=15, null=True, unique=True)),
                ('verification_id', models.CharField(max_length=30, null=True, unique=True)),
                ('is_pan_verify', models.BooleanField(default=False)),
                ('is_gst_verify', models.BooleanField(default=False)),
                ('aadhaar_card_number', models.CharField(max_length=12, null=True, unique=True)),
                ('docs_files', models.JSONField(null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('gst_number', models.CharField(max_length=15, null=True, unique=True)),
                ('gst_type', models.CharField(choices=[('Composition', 'Composition'), ('Regular', 'Regular'), ('Unregister', 'Unregister'), ('SEZ', 'SEZ'), ('Exports', 'Exports'), ('Ecommerce', 'Ecommerce')], default='Composition', max_length=15)),
                ('admin_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APROVE', 'APROVE'), ('REJECT', 'REJECT')], default='PENDING', max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(null=True)),
                ('admin_pdf', models.FileField(blank=True, null=True, upload_to='admin_pdfs/')),
            ],
            options={
                'db_table': 'sa_admin',
            },
        ),
        migrations.CreateModel(
            name='AdminAgreement',
            fields=[
                ('aa_id', models.AutoField(primary_key=True, serialize=False)),
                ('aa_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('agreement_document', models.FileField(null=True, upload_to='agreement_document/')),
                ('aa_status', models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('EXPIRED', 'EXPIRED')], default='IN PROGRESS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_admin_agreement',
            },
        ),
        migrations.CreateModel(
            name='AdminBankDetails',
            fields=[
                ('bd_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposite_category', models.JSONField()),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=128, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=128, null=True)),
                ('account_type', models.CharField(blank=True, max_length=128, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
            ],
            options={
                'db_table': 'sa_bank_detail',
            },
        ),
        migrations.CreateModel(
            name='AdminFundRequest',
            fields=[
                ('fr_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposite_category', models.JSONField()),
                ('deposite_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('utr_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('transaction_mode', models.CharField(blank=True, choices=[('IMPS', 'Imps'), ('RTGS', 'Rtgs'), ('NEFT', 'Neft')], max_length=128, null=True)),
                ('payment_proof', models.JSONField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=255)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(db_column='updated_by', null=True)),
            ],
            options={
                'db_table': 'sa_fund_request',
            },
        ),
        migrations.CreateModel(
            name='AdminService',
            fields=[
                ('admin_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('charges', models.JSONField(null=True)),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_admin_service',
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('charges_id', models.AutoField(primary_key=True, serialize=False)),
                ('charges_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('rate_type', models.CharField(choices=[('is_flat', 'Is_Flat'), ('is_percent', 'Is_Percent')], max_length=20)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge_category', models.CharField(choices=[('to_us', 'To Us'), ('to_provide', 'To Provide')], default='to_us', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_charges',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.IntegerField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sa_city',
            },
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateTimeField()),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_payment_type', models.CharField(choices=[('credit card', 'Credit Card'), ('bank transfer', 'Bank Transfer'), ('cash', 'Cash'), ('online', 'Online'), ('other', 'Other')], max_length=20)),
                ('expense_transaction_receipt_no', models.CharField(max_length=150, null=True)),
                ('expense_type', models.CharField(choices=[('taxed', 'Taxed'), ('non-taxed', 'Non-Taxed')], max_length=20)),
                ('expense_tax_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expense_tax_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('firm_name', models.CharField(max_length=150, null=True)),
                ('gst_no', models.CharField(max_length=150, null=True)),
                ('expense_description', models.TextField()),
                ('expense_attachment', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_expense',
            },
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('ft_id', models.AutoField(primary_key=True, serialize=False)),
                ('ft_type', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_fees_type',
            },
        ),
        migrations.CreateModel(
            name='HSNSAC',
            fields=[
                ('hsnsac_id', models.AutoField(primary_key=True, serialize=False)),
                ('hsnsac_code', models.CharField(max_length=255, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_hsnsac',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('product_img', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('category_description', models.TextField()),
                ('parent_category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_product_category',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocumentList',
            fields=[
                ('rdl_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=80)),
                ('is_required', models.BooleanField(default=False)),
                ('document_name', models.CharField(max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_slug', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'sa_required_document_list',
            },
        ),
        migrations.CreateModel(
            name='SaBBPSBillerCategory',
            fields=[
                ('bbps_id', models.AutoField(primary_key=True, serialize=False)),
                ('bbps_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_us_charges', models.JSONField(blank=True, null=True)),
                ('to_provide_charges', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deactive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'sa_bbps_biller_category',
            },
        ),
        migrations.CreateModel(
            name='SaOprators',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(blank=True, max_length=55, null=True)),
                ('operator_code', models.CharField(blank=True, max_length=55, null=True)),
                ('to_us_charges', models.JSONField(blank=True, null=True)),
                ('to_provide_charges', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deactive', models.BooleanField(blank=True, default=False, null=True)),
                ('operator_type', models.CharField(blank=True, max_length=55, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sa_operators',
            },
        ),
        migrations.CreateModel(
            name='SaService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_service',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(max_length=150, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tds_type', models.CharField(blank=True, choices=[('WITH TDS', 'WITH TDS'), ('WITHOUT TDS', 'WITHOUT TDS')], max_length=255, null=True)),
                ('service_nature', models.CharField(blank=True, choices=[('charges', 'Charges'), ('commission', 'Commission')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sa_service_provider',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.IntegerField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sa_state',
            },
        ),
    ]
