# Generated by Django 5.1.5 on 2025-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
