# Generated by Django 5.1.5 on 2025-02-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_remove_serviceprovider_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminservice',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_admin', to='control_panel.admin'),
        ),
    ]
