# Generated by Django 5.1.5 on 2025-02-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_alter_adminservice_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbankdetails',
            name='cdm_charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminbankdetails',
            name='counter_charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminbankdetails',
            name='online_charges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
