# Generated by Django 5.1.5 on 2025-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_adminbankdetails_cdm_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='credentials_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='plateform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='plateform_fee_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='required_key',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
