# Generated by Django 5.1.5 on 2025-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_serviceprovider_credentials_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaPgConfiged',
            fields=[
                ('configed_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_network', models.CharField(blank=True, max_length=50, null=True)),
                ('card_sub_type', models.CharField(blank=True, max_length=10, null=True)),
                ('to_us_charges', models.JSONField(blank=True, null=True)),
                ('to_provide_charges', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deactive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sa_pg_configed',
            },
        ),
    ]
