# Generated by Django 5.1.5 on 2025-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_sapgconfiged'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapgconfiged',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
