# Generated by Django 5.1.5 on 2025-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_sapgconfiged_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saservice',
            name='config_table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saservice',
            name='is_table_config',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
