# Generated by Django 5.1.5 on 2025-02-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_saservice_config_table_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabbpsbillercategory',
            old_name='bbps_id',
            new_name='ss_id',
        ),
        migrations.RenameField(
            model_name='sabbpsbillercategory',
            old_name='bbps_category_name',
            new_name='ss_name',
        ),
        migrations.RenameField(
            model_name='saoprators',
            old_name='operator_id',
            new_name='ss_id',
        ),
        migrations.RenameField(
            model_name='saoprators',
            old_name='operator_name',
            new_name='ss_name',
        ),
        migrations.RenameField(
            model_name='sapgconfiged',
            old_name='configed_id',
            new_name='ss_id',
        ),
    ]
