# Generated by Django 5.1.5 on 2025-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_saphonepepgconfiged'),
    ]

    operations = [
        migrations.AddField(
            model_name='saoprators',
            name='recharge_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
