# Generated by Django 5.1.5 on 2025-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0013_remove_saservice_config_table_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saphonepepgconfiged',
            name='card_sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saphonepepgconfiged',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
