# Generated by Django 5.1.5 on 2025-02-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_alter_saphonepepgconfiged_card_sub_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaOtherCharges',
            fields=[
                ('oc_id', models.AutoField(primary_key=True, serialize=False)),
                ('oc_name', models.CharField(blank=True, max_length=125, null=True)),
                ('charge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('hsn_sac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control_panel.hsnsac')),
            ],
            options={
                'db_table': 'sa_other_charges',
            },
        ),
    ]
