# Generated by Django 5.1.5 on 2025-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_saothercharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapgconfiged',
            name='card_sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapgconfiged',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
