# Generated by Django 5.1.5 on 2025-01-27 09:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('totp_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=128, null=True)),
                ('verify_code_expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'sa_custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('about_us_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us_desc', models.TextField(null=True)),
                ('our_focus_desc', models.TextField(null=True)),
                ('our_mission_desc', models.TextField(null=True)),
                ('our_vision_desc', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_about_us',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('announcement_type', models.CharField(choices=[('Service Update', 'Service Update'), ('Regulatory Compliance', 'Regulatory Compliance'), ('security Alerts', 'security Alerts'), ('Product Launches', 'Product Launches'), ('Service Interruptions', 'Service Interruptions'), ('Industry News', 'Industry News'), ('Policy Updates', 'Policy Updates')], max_length=50)),
                ('date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('attachment_doc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='announcement_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_announcement',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_for_web', models.ImageField(upload_to='Banners/Web/')),
                ('image_for_mobile', models.ImageField(upload_to='Banners/Mobile/')),
                ('description', models.TextField()),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_banner',
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('ce_id', models.AutoField(primary_key=True, serialize=False)),
                ('ce_name', models.CharField(max_length=255)),
                ('ce_email', models.EmailField(max_length=255)),
                ('ce_contact_no', models.CharField(max_length=15)),
                ('ce_subject', models.CharField(max_length=255)),
                ('ce_message', models.TextField()),
                ('ce_status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('update_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_contact_enquiry',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contactus_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('social_media_links', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_contact_us',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('loginlog_id', models.AutoField(primary_key=True, serialize=False)),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('browser_name', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sa_login_log',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('broadcast_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_news_letter',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='Partners/Logos/')),
                ('description', models.TextField()),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_partner',
            },
        ),
        migrations.CreateModel(
            name='Randomstuff',
            fields=[
                ('randomstuff_id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy_policy_desc', models.TextField(null=True)),
                ('terms_of_service_desc', models.TextField(null=True)),
                ('cancellation_policy_desc', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_random_stuff',
            },
        ),
        migrations.CreateModel(
            name='SaUserActivity',
            fields=[
                ('ua_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('ua_action', models.CharField(max_length=100)),
                ('ua_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.TextField(null=True)),
                ('response_data', models.TextField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_user_activity',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('servicegroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('group_name', models.CharField(max_length=255)),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_service_group',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Services/')),
                ('description', models.TextField()),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='web_portal.servicegroup')),
            ],
            options={
                'db_table': 'web_service',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('smtpconfig_id', models.AutoField(primary_key=True, serialize=False)),
                ('smtp_server', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(null=True)),
                ('password', models.CharField(max_length=255)),
                ('encryption_method', models.CharField(choices=[('SSL/TLS', 'SSL/TLS'), ('STARTTLS', 'STARTTLS')], max_length=10)),
                ('sender_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='smtpconfig_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtpconfig_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_smtp_configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Review', 'Review'), ('Closed', 'Closed')], default='Pending', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_testimonial',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('youtubevideo_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255)),
                ('youtube_link', models.URLField()),
                ('youtube_thumbnail_image', models.ImageField(upload_to='Youtube/Thumbnails/')),
                ('is_deactive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_youtube_video',
            },
        ),
    ]
