# Generated by Django 5.1.5 on 2025-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gltrn',
            name='service_trn_table',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
