# Generated by Django 5.1.5 on 2025-01-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0002_gltrn_service_trn_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilerecharge',
            name='mr_sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adserviceprovider'),
        ),
    ]
