# Generated by Django 5.1.5 on 2025-01-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0003_mobilerecharge_mr_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpsbillpayment',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
