# Generated by Django 5.1.5 on 2025-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0004_bbpsbillpayment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysprintdmtcustomer',
            name='customer_amount_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
