# Generated by Django 5.1.5 on 2025-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0005_paysprintdmtcustomer_customer_amount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmttransaction',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
