# Generated by Django 5.1.5 on 2025-01-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0006_dmttransaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilerecharge',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgservicetrn',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pyotservicetrn',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
