# Generated by Django 5.1.5 on 2025-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0007_mobilerecharge_created_by_pgservicetrn_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adserviceprovider',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
