# Generated by Django 5.1.5 on 2025-02-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0008_remove_adserviceprovider_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluserdetails',
            name='pu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
        migrations.AlterField(
            model_name='portaluserloginlogs',
            name='pu_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
        migrations.AlterField(
            model_name='portaluserwallet',
            name='pu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser', unique=True),
        ),
    ]
