# Generated by Django 5.1.5 on 2025-02-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0010_alter_gltrn_pu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettrn',
            name='pu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
    ]
