# Generated by Django 5.1.5 on 2025-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0011_alter_wallettrn_pu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysprintdmtbankaccount',
            old_name='is_verified',
            new_name='is_verified_1',
        ),
        migrations.AddField(
            model_name='paysprintdmtbankaccount',
            name='is_verified_2',
            field=models.BooleanField(default=False),
        ),
    ]
