# Generated by Django 5.1.5 on 2025-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0012_rename_is_verified_paysprintdmtbankaccount_is_verified_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adservice',
            name='config_table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adservice',
            name='is_table_config',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
