# Generated by Django 5.1.5 on 2025-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0013_adservice_config_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprators',
            name='recharge_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
