# Generated by Django 5.1.5 on 2025-02-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0014_oprators_recharge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfPgServiceTrn',
            fields=[
                ('cf_pg_service_trn_id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_pg_trn_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cf_pg_customer_id', models.CharField(blank=True, max_length=13, null=True)),
                ('cf_pg_trn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('cf_pg_trn_response', models.JSONField(blank=True, null=True)),
                ('cf_pg_aadhaar_response', models.JSONField(blank=True, null=True)),
                ('cf_pg_customer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('cf_pg_customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cf_pg_customer_aadhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('cf_pg_customer_contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('cf_pg_contact_verify_code', models.CharField(blank=True, max_length=128, null=True)),
                ('cf_pg_verify_code_expire_at', models.DateTimeField(blank=True, null=True)),
                ('cf_pg_trn_status', models.CharField(blank=True, default='PENDING', max_length=15, null=True)),
                ('cf_pg_service_trn_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adserviceprovider')),
            ],
            options={
                'db_table': 'ad_cashfree_pg_service_transaction',
            },
        ),
    ]
