# Generated by Django 5.1.5 on 2025-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0015_cfpgservicetrn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfpgservicetrn',
            old_name='cf_pg_customer_aadhaar_no',
            new_name='cf_pg_customer_pan_no',
        ),
        migrations.RenameField(
            model_name='cfpgservicetrn',
            old_name='cf_pg_aadhaar_response',
            new_name='cf_pg_ekyc_document',
        ),
        migrations.AddField(
            model_name='cfpgservicetrn',
            name='cf_pg_is_kyc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
