# Generated by Django 5.1.5 on 2025-02-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0016_rename_cf_pg_customer_aadhaar_no_cfpgservicetrn_cf_pg_customer_pan_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfPgCustomer',
            fields=[
                ('cf_pg_customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_pg_ekyc_document', models.JSONField(blank=True, null=True)),
                ('cf_pg_customer_contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('cf_pg_customer_pan_no', models.CharField(blank=True, max_length=12, null=True)),
                ('cf_pg_contact_verify_code', models.CharField(blank=True, max_length=128, null=True)),
                ('cf_pg_verify_code_expire_at', models.DateTimeField(blank=True, null=True)),
                ('cf_pg_is_kyc', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ad_cashfree_pg_customer',
            },
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_contact_verify_code',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_customer_email',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_customer_id',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_customer_name',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_customer_pan_no',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_ekyc_document',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_is_kyc',
        ),
        migrations.RemoveField(
            model_name='cfpgservicetrn',
            name='cf_pg_verify_code_expire_at',
        ),
        migrations.AddField(
            model_name='cfpgservicetrn',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.cfpgcustomer'),
        ),
    ]
