# Generated by Django 5.1.5 on 2025-02-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0017_cfpgcustomer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cfpgservicetrn',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
