# Generated by Django 5.1.5 on 2025-02-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0018_rename_customer_id_cfpgservicetrn_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_dt_charges',
            new_name='dt_charges',
        ),
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_md_charges',
            new_name='md_charges',
        ),
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_rt_charges',
            new_name='rt_charges',
        ),
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_sd_charges',
            new_name='sd_charges',
        ),
    ]
