# Generated by Django 5.1.5 on 2025-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0019_rename_bbps_dt_charges_bbpsbillercategory_dt_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='charges_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
