# Generated by Django 5.1.5 on 2025-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0020_bankdetails_charges_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='charges_json',
            new_name='cdm_charges',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='counter_charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='online_charges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
