# Generated by Django 5.1.5 on 2025-02-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0021_rename_charges_json_bankdetails_cdm_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBPSComplaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('trn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('complaint_response', models.JSONField(blank=True, null=True)),
                ('tracking_response', models.JSONField(blank=True, null=True)),
                ('complaint_status', models.CharField(blank=True, default='PENDING', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'ad_bbps_complaint',
            },
        ),
    ]
