# Generated by Django 5.1.5 on 2025-02-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0022_bbpscomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbpscomplaint',
            name='comp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
