# Generated by Django 5.1.5 on 2025-02-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0023_bbpscomplaint_comp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='hsn_sac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adhsnsac'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
