# Generated by Django 5.1.5 on 2025-02-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0024_bankdetails_hsn_sac_alter_bankdetails_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='hsn_sac',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
    ]
