# Generated by Django 5.1.5 on 2025-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0025_remove_bankdetails_hsn_sac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adserviceprovider',
            name='is_self_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='plateform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='plateform_fee_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='required_key',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
