# Generated by Django 5.1.5 on 2025-02-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0028_cfpgconfiged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CfPgConfiged',
            new_name='AdCfPgConfiged',
        ),
    ]
