# Generated by Django 5.1.5 on 2025-02-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0030_adcfpgconfiged_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adcfpgconfiged',
            old_name='configed_id',
            new_name='ss_id',
        ),
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_id',
            new_name='ss_id',
        ),
        migrations.RenameField(
            model_name='bbpsbillercategory',
            old_name='bbps_category_name',
            new_name='ss_name',
        ),
        migrations.RenameField(
            model_name='oprators',
            old_name='operator_id',
            new_name='ss_id',
        ),
        migrations.RenameField(
            model_name='oprators',
            old_name='operator_name',
            new_name='ss_name',
        ),
    ]
