# Generated by Django 5.1.5 on 2025-02-21 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0031_rename_configed_id_adcfpgconfiged_ss_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePeTransaction',
            fields=[
                ('pp_trn_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp_marchant_trn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('pp_contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('pp_pay_response', models.JSONField(blank=True, null=True)),
                ('pp_trn_response', models.JSONField(blank=True, null=True)),
                ('pp_status', models.CharField(blank=True, default='PENDING', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adserviceprovider')),
            ],
            options={
                'db_table': 'ad_pp_service_transaction',
            },
        ),
    ]
