# Generated by Django 5.1.5 on 2025-02-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0032_phonepetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePeConfiged',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_network', models.CharField(blank=True, max_length=50, null=True)),
                ('card_sub_type', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('sd_charges', models.JSONField(blank=True, null=True)),
                ('md_charges', models.JSONField(blank=True, null=True)),
                ('dt_charges', models.JSONField(blank=True, null=True)),
                ('rt_charges', models.JSONField(blank=True, null=True)),
                ('to_us_charges', models.JSONField(blank=True, null=True)),
                ('sa_provided', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ad_phonepe_pg_configed',
            },
        ),
        migrations.AlterModelTable(
            name='phonepetransaction',
            table='ad_phonepe_service_transaction',
        ),
    ]
