# Generated by Django 5.1.5 on 2025-02-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0033_phonepeconfiged_alter_phonepetransaction_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('oc_id', models.AutoField(primary_key=True, serialize=False)),
                ('oc_name', models.CharField(blank=True, max_length=125, null=True)),
                ('charge_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('minimum', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_deactive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('hsn_sac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.adhsnsac')),
            ],
            options={
                'db_table': 'ad_other_charges',
            },
        ),
    ]
