# Generated by Django 5.1.5 on 2025-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0034_othercharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluserwallet',
            name='os_wallet',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
