# Generated by Django 5.1.5 on 2025-02-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0035_portaluserwallet_os_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpTransaction',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_wallet', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('effective_type', models.CharField(blank=True, max_length=10, null=True)),
                ('tt_trn_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('tt_trn_status', models.CharField(blank=True, default='PENDING', max_length=100, null=True)),
                ('tt_trn_dt', models.DateTimeField(auto_now_add=True)),
                ('is_settle_with_cash', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser')),
            ],
            options={
                'db_table': 'ad_topup_transaction',
            },
        ),
    ]
