# Generated by Django 5.1.5 on 2025-02-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0036_topuptransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topuptransaction',
            old_name='effective_amount',
            new_name='tt_amount',
        ),
        migrations.RemoveField(
            model_name='topuptransaction',
            name='effective_type',
        ),
        migrations.RemoveField(
            model_name='topuptransaction',
            name='effective_wallet',
        ),
        migrations.RemoveField(
            model_name='topuptransaction',
            name='pu',
        ),
    ]
