# Generated by Django 5.1.5 on 2025-02-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0037_rename_effective_amount_topuptransaction_tt_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerBankDetails',
            fields=[
                ('rbd_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=128, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=128, null=True)),
                ('account_type', models.CharField(blank=True, max_length=128, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('rdb_status', models.CharField(blank=True, default='PENDING', max_length=128, null=True)),
                ('is_deactive', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='updated_by', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser')),
            ],
            options={
                'db_table': 'ad_retailer_bank_detail',
            },
        ),
    ]
