# Generated by Django 5.1.5 on 2025-02-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0038_retailerbankdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailerbankdetails',
            old_name='rdb_status',
            new_name='rbd_status',
        ),
    ]
