# Generated by Django 5.1.5 on 2025-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0039_rename_rdb_status_retailerbankdetails_rbd_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adservice',
            name='config_table_name',
        ),
        migrations.RemoveField(
            model_name='adservice',
            name='is_table_config',
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='config_table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='is_table_config',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
