# Generated by Django 5.1.5 on 2025-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0040_remove_adservice_config_table_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonepeconfiged',
            name='card_sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phonepeconfiged',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
