# Generated by Django 5.1.5 on 2025-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0041_alter_phonepeconfiged_card_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbpsbillercategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
