# Generated by Django 5.1.5 on 2025-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0042_alter_bbpsbillercategory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcfpgconfiged',
            name='card_sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adcfpgconfiged',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
