# Generated by Django 5.1.5 on 2025-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0043_alter_adcfpgconfiged_card_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('WEB BANNER', 'WEB BANNER'), ('MOBILE BANNER', 'MOBILE BANNER'), ('LOGIN PAGE BANNER', 'LOGIN PAGE BANNER'), ('RETAILER DASHBOARD PAGE', 'RETAILER DASHBOARD PAGE')], max_length=50),
        ),
    ]
