# Generated by Django 5.1.5 on 2025-03-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0044_banner_banner_url_alter_banner_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluserloginlogs',
            name='ip_address',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('WEB BANNER', 'WEB BANNER'), ('MOBILE BANNER', 'MOBILE BANNER'), ('LOGIN PAGE BANNER', 'LOGIN PAGE BANNER'), ('RETAILER DASHBOARD PAGE', 'RETAILER DASHBOARD PAGE'), ('DISTRIBUTOR DASHBOARD PAGE', 'DISTRIBUTOR DASHBOARD PAGE')], max_length=50),
        ),
    ]
