# Generated by Django 5.1.5 on 2025-03-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0045_portaluserloginlogs_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('an_id', models.AutoField(primary_key=True, serialize=False)),
                ('an_title', models.CharField(blank=True, max_length=255, null=True)),
                ('an_desc', models.TextField(blank=True, null=True)),
                ('an_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deactive', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser')),
            ],
            options={
                'db_table': 'ad_announcement',
            },
        ),
    ]
