# Generated by Django 5.1.5 on 2025-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0046_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettrn',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
