# Generated by Django 5.1.5 on 2025-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0047_wallettrn_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcharges',
            name='maximum',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adcharges',
            name='minimum',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adcharges',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adcommissioncharges',
            name='maximum',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adcommissioncharges',
            name='minimum',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adcommissioncharges',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adserviceprovider',
            name='plateform_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adserviceprovider',
            name='tds_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='airtelcmstrn',
            name='trn_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='airtelcmstrn',
            name='trn_commission',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='bbpsbillpayment',
            name='bbps_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cfpgservicetrn',
            name='cf_pg_trn_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='dmttransaction',
            name='dmt_txn_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='deposite_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='effectvie_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='gl_tax_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='gl_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='gl_tds_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='gl_tds_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='gltrn',
            name='gl_trn_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='mobilerecharge',
            name='mr_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='othercharges',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='othercharges',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='othercharges',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='py_trn_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='pgservicetrn',
            name='pg_trn_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='phonepetransaction',
            name='pp_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='portaluserwallet',
            name='cashin_wallet',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='portaluserwallet',
            name='os_wallet',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='portaluserwallet',
            name='pg_wallet',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pyotservicetrn',
            name='trn_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='tt_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallettrn',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='wallettrn',
            name='effectvie_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
    ]
