# Generated by Django 5.1.5 on 2025-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0048_alter_adcharges_maximum_alter_adcharges_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfpgservicetrn',
            name='cf_pg_settle_status',
            field=models.CharField(blank=True, default='PENDING', max_length=15, null=True),
        ),
    ]
