# Generated by Django 5.1.5 on 2025-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0049_cfpgservicetrn_cf_pg_settle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfpgservicetrn',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
