# Generated by Django 5.1.5 on 2025-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0050_cfpgservicetrn_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfpgservicetrn',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
