# Generated by Django 5.1.5 on 2025-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0051_cfpgservicetrn_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='pu_contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
