# Generated by Django 5.1.5 on 2025-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0052_alter_portaluser_pu_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysprintdmtbankaccount',
            name='verify_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paysprintdmtbankaccount',
            name='verify_code_expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
