# Generated by Django 5.1.5 on 2025-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0053_paysprintdmtbankaccount_verify_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtbanklist',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dmtbanklist',
            name='bank_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmtbanklist',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
