# Generated by Django 5.1.5 on 2025-03-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0054_dmtbanklist_bank_ifsc_alter_dmtbanklist_bank_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DMTBankList',
            new_name='GlobalBankList',
        ),
        migrations.AlterModelTable(
            name='globalbanklist',
            table='ad_Global_bank_list',
        ),
    ]
