# Generated by Django 5.1.5 on 2025-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0055_rename_dmtbanklist_globalbanklist_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pyotservicetrn',
            table='ad_payout_service_transaction',
        ),
    ]
