# Generated by Django 5.1.5 on 2025-03-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0056_alter_pyotservicetrn_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalbanklist',
            table='ad_global_bank_list',
        ),
    ]
